version: '2'
services:
  etcd:
    image: chanwit/kine:v0.6.0
    networks:
      fluxnet:
        aliases:
          - etcd
    command: [
      "/bin/kine",
      "--listen-address=tcp://0.0.0.0:2379",
      "--endpoint=sqlite"
    ]
  apiserver:
    image: gcr.io/google_containers/kube-apiserver-amd64:v1.18.6
    networks:
      fluxnet:
        aliases:
          - apiserver
    ports:
      - "8080:8080"
    privileged: true
    command: [
      "kube-apiserver", "--etcd-servers", "http://etcd:2379",
      "--service-cluster-ip-range", "10.96.0.0/16",
      "--insecure-port", "8080",
      "-v", "2",
      "--insecure-bind-address", "0.0.0.0"
    ]
  source:
    image: ghcr.io/fluxcd/source-controller:v0.8.1
    networks:
      fluxnet:
        aliases:
          - source
          - source-controller
    restart: always
    user: 1000:1000
    volumes:
      - $PWD/kubeconfig:/kubeconfig
      - $PWD/data:/data
    environment:
      - KUBECONFIG=/kubeconfig
      - RUNTIME_NAMESPACE=flux-system
    command: [
      "--events-addr=http://notification-controller/",
      "--watch-all-namespaces=true",
      "--log-level=debug",
      "--log-encoding=json",
      "--storage-path=/data",
      "--storage-adv-addr=source-controller:9090",
    ]
  kustomize:
    image: ghcr.io/fluxcd/kustomize-controller:v0.8.1
    networks:
      fluxnet:
        aliases:
          - kustomize
          - kustomize-controller
    restart: always
    user: 1000:1000
    volumes:
      - $PWD/kubeconfig:/kubeconfig
    environment:
      - KUBECONFIG=/kubeconfig
      - RUNTIME_NAMESPACE=flux-system
    command: [
      "--watch-all-namespaces=true",
      "--log-level=debug",
      "--log-encoding=json"
    ]
  controller:
    build:
      context: ./controller
    volumes:
      - $PWD/kubeconfig:/kubeconfig
    networks:
      fluxnet:
        aliases:
          - controller
    restart: always
    environment:
      - KUBECONFIG=/kubeconfig
    command: [
      "kopf", "run",
      "/src/controller.py",
      "--standalone",
      "--verbose"
    ]

networks:
  fluxnet:
    driver: bridge
