---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: edge
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./edge
  prune: true
  sourceRef:
    kind: GitRepository
    name: edge
  validation: client

