# A demo CRD for the Kopf example operators.
# Use it with Kubernetes 1.16 and above.
# For Kubernetes 1.15 and below, use crd-v1beta1.yaml.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: compose.f0x.dev
spec:
  scope: Namespaced
  group: f0x.dev
  names:
    kind: Compose
    plural: compose
    singular: compose
    shortNames:
      - compose
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Duration
          type: string
          priority: 0
          jsonPath: .spec.duration
          description: For how long the pod should sleep.
        - name: Children
          type: string
          priority: 0
          jsonPath: .status.create.children
          description: The children pods created.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create.message
          description: As returned from the handler (sometimes).
